# Generated by Django 4.1.1 on 2022-10-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='read',
            new_name='accepted',
        ),
    ]
