# Generated by Django 4.1.1 on 2022-10-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_read_comment_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
